eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
okta:
  oauth2:
    issuer: https://dev-13713500.okta.com/oauth2/default
    audience: api://default
